"use strict";

const { post } = require("superagent");
const db = require("../db");
const { NotFoundError} = require("../expressError");
const { sqlForPartialUpdate } = require("../helpers/sql");
const moment = require("moment");
const axios = require("axios");


/** Related functions for posts. */

class Post {

  /** Given a post category, return posts by category.
   *
   * Returns { title, content, image, post_date, category }
   *
   * Throws NotFoundError if not found.
   **/

 static async getPostsByCat(cat) {

    const q = `SELECT *
                FROM posts
                WHERE cat = $1::text`
                              
                                
    const postRes = await db.query(q, [cat]);
    
    const posts = postRes.rows;

    if (!posts) throw new NotFoundError(`No posts with category: ${cat}`);

    return posts;
  }


  /** Return all posts.
   *
   * Returns { title, content, image, post_date, category }
   *
   * Throws NotFoundError if no posts.
   **/

  static async getAllPosts(){
    let q = `SELECT * FROM posts`;

    const res = await db.query(q);

    const postRes = res.rows;

    if(!postRes) throw new NotFoundError(`No current posts. Post something!`);
    
    return postRes;
  }


  /** Given a post ID, return post by ID.
   *
   * Returns { title, content, image, post_date, category }
   *
   * Throws NotFoundError if not found.
   **/

  static async getPostById(id){

    const getPost = await db.query(
        `SELECT u.username, title, content, p.img, u.profile_img, cat, post_date
        FROM users u 
        JOIN posts p ON u.id = p.user_id
        WHERE p.id = $1`, [id]
    )
    
    const post = getPost.rows[0];

    if(!post) throw new NotFoundError(`Oops! This post may have been deleted or moved.`)
    
    return post;
  }


  /** When updating a post, return original post by ID.
   *
   * Returns { title, content, image, post_date, category }
   *
   * Throws NotFoundError if not found.
   **/

  static async getPostForUpdate(id){
    
    const getPost = await db.query(
        `SELECT p.title, p.content, p.img, p.cat, p.post_date, p.user_id
        FROM users u 
        JOIN posts p ON u.id = p.user_id
        WHERE p.id = $1`, [id]
    )
    
    const post = getPost.rows[0];

    if(!post) throw new NotFoundError(`Oops! This post may have been deleted or moved.`)
    
    return post;
  }


  /** Removes post permanently and alerts user of success
   * 
   * Throws NotFoundError if not found.
   **/

  static async removePost(id){
      const res = await db.query(
          `DELETE FROM posts
          WHERE id = $1
          RETURNING id`, [id]
      )

      const post = res.rows[0];

      if(!post) throw new NotFoundError(`No post to delete with id of ${id}`)
  }


  /** Create post if user is signed in. 
   *
   * Returns { title, content, image, post_date, category and user_id }
   * 
   * Image is autogenerated via external API call if no image is provided
   * Post_date autogenerated using moment api.
   **/

  static async addPost({title, content, img, post_date, cat, user_id}){
      const date = moment().format("dddd, MMMM Do YYYY, h:mm:ss a")

      const photo = await axios.get('https://picsum.photos/400')
      let generatePhoto = photo.request.res.responseUrl;
      img === "" ? img = generatePhoto : img
  
      const res = await db.query(
          `INSERT INTO posts
          (title, content, img, post_date, cat, user_id) 
          VALUES ($1, $2, $3, $4, $5, $6)
            RETURNING id, title, content, img, post_date, cat, user_id`,
        [title,
            content,
            img,
            date,
            cat,
            user_id]
      );

      const newPost = res.rows[0];

      return newPost;
  }

  // Updates users post using sqlForPartialUpdate
  
  static async update(id, data) {
    const { setCols, values } = sqlForPartialUpdate(
        data,
        {});
    const idVarIdx = "$" + (values.length + 1);

    const querySql = `UPDATE posts 
                      SET ${setCols} 
                      WHERE id = ${idVarIdx} 
                      RETURNING id, 
                                title, 
                                content, 
                                img,
                                cat`;
    const result = await db.query(querySql, [...values, id]);
    const post = result.rows[0];

    if (!post) throw new NotFoundError(`No post: ${id}`);

    return post;
  }

}

module.exports = Post;

